import logging
from fastapi import APIRouter, HTTPException
from app.models.api_models import AskRequest, AskResponse
from app.services.nebula_client import nebula_client
from app.services.ai_wrapper import ai_wrapper

logger = logging.getLogger(__name__)

router = APIRouter()

@router.post("/ask", response_model=AskResponse)
async def ask_utd_buddy(request: AskRequest):
    """
    Receives a question from Godot, fetches UTD context from Nebula, 
    and returns a conversational answer generated by Gemini.
    """
    question = request.question.strip()
    
    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    
    # 1. Ask Gemini to extract intent (course vs professor and the param mapping)
    logger.info(f"Extracting intent for: {question}")
    intent_data = ai_wrapper.extract_intent(question)
    
    endpoint = intent_data.get("endpoint", "none")
    params = intent_data.get("params", {})
    
    logger.info(f"Routed intent -> endpoint: {endpoint}, params: {params}")
    
    # 2. Fetch specific Context from Nebula based on intent
    nebula_context = {}
    
    if endpoint == "course":
        nebula_response = nebula_client.search_course(params)
    elif endpoint == "professor":
        nebula_response = nebula_client.search_professor(params)
    else:
        # If Gemini couldn't map it, or thinks it's a generic question, we don't query Nebula
        nebula_response = {"results": [], "message": "No relevant UTD data needed."}
        
    # Check if there was an error in the Nebula response
    if "error" in nebula_response:
        logger.warning(f"Nebula context retrieval failed: {nebula_response['error']}")
        nebula_context = {"warning": "Nebula API Unavailable", "details": nebula_response}
    else:
        nebula_context = nebula_response
    
    # 3. Generate Conversation with Gemini using the targeted context
    logger.info("Generating Gemini response...")
    ai_answer = ai_wrapper.generate_response(question, nebula_context)
    
    # 4. Return JSON back to Godot
    return AskResponse(answer=ai_answer)
