import logging
from fastapi import APIRouter, HTTPException
from app.models.api_models import AskRequest, AskResponse
from app.services.nebula_client import nebula_client
from app.services.ai_wrapper import ai_wrapper

logger = logging.getLogger(__name__)

router = APIRouter()

@router.post("/ask", response_model=AskResponse)
async def ask_utd_buddy(request: AskRequest):
    """
    Receives a question from Godot, fetches UTD context from Nebula, 
    and returns a conversational answer generated by Gemini.
    """
    question = request.question.strip()
    
    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    
    # 1. Fetch Context from Nebula
    logger.info(f"Querying Nebula for: {question}")
    nebula_response = nebula_client.search(question)
    
    # Check if there was an error in the Nebula response
    if "error" in nebula_response:
        logger.warning(f"Nebula context retrieval failed: {nebula_response['error']}")
        # We can either fail here, or pass an empty context to Gemini. 
        # We'll pass the error as context and Gemini will tell the user it couldn't find UTD data.
        nebula_context = {"warning": "Nebula API Unavailable", "details": nebula_response}
    else:
        # Pass the structured data forward to Gemini
        nebula_context = nebula_response
    
    # 2. Generate Conversation with Gemini
    logger.info("Generating Gemini response...")
    ai_answer = ai_wrapper.generate_response(question, nebula_context)
    
    # 3. Return JSON back to Godot
    return AskResponse(answer=ai_answer)
